// User
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SHOW_LOGOUT = "SHOW_LOGOUT";
//Message
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
//Confirm Dialog
export const SET_SHOW_CONFIRM = "SET_SHOW_CONFIRM";
export const CLEAR_SHOW_CONFIRM = "CLEAR_SHOW_CONFIRM";
//Error Dialog
export const SET_SHOW_ERROR = "SET_SHOW_ERROR";
export const CLEAR_SHOW_ERROR = "CLEAR_SHOW_ERROR";
//Line worker
export const SET_WORK_START = "SET_WORK_START";
export const CLEAR_WORK_START = "CLEAR_WORK_START";
export const SET_LINE_CHOICE = "SET_LINE_CHOICE";
export const CLEAR_LINE_CHOICE = "CLEAR_LINE_CHOICE";
export const SET_FLAG_SCAN_PRODUCT = "SET_FLAG_SCAN_PRODUCT";
export const SET_SCAN_PRODUCT = "SET_SCAN_PRODUCT";
export const CLEAR_SCAN_PRODUCT = "CLEAR_SCAN_PRODUCT";
export const SET_SHOW_PROCESS = "SET_SHOW_PROCESS";
export const CLEAR_SHOW_PROCESS = "CLEAR_SHOW_PROCESS";
export const LINE_LOGOUT = "LINE_LOGOUT";
export const SET_NET_PROCESS = "SET_NET_PROCESS";
export const SET_SHOW_DETAIL = "SET_SHOW_DETAIL";
export const CLEAR_SHOW_DETAIL = "CLEAR_SHOW_DETAIL";
export const SET_SEN_MEMO = "SET_SEN_MEMO";
export const SET_ERROR_MEMO = "SET_ERROR_MEMO";

//Admin
export const SET_LEFT_MENU_SELECT = "SET_LEFT_MENU_SELECT";
export const SET_SHOW_PROCESS_SETTING = "SET_SHOW_PROCESS_SETTING";
export const CLEAR_SHOW_PROCESS_SETTING = "CLEAR_SHOW_PROCESS_SETTING";
export const SET_PROCESS_SETTING_TAB_SELECT = "SET_PROCESS_SETTING_TAB_SELECT";
export const SET_SHOW_CONFIRM_DELETE_USER = "SET_SHOW_CONFIRM_DELETE_USER";
export const CLEAR_SHOW_CONFIRM_DELETE_USER = "CLEAR_SHOW_CONFIRM_DELETE_USER";
export const SET_SHOW_ADD_USER_DIALOG = "SET_SHOW_ADD_USER_DIALOG";
export const CLEAR_SHOW_ADD_USER_DIALOG = "CLEAR_SHOW_ADD_USER_DIALOG";
